<a href="https://colab.research.google.com/github/georgsmeinung/rn1-perceptron/blob/main/RN-Clase03/NeuronaNoLineal-Multiclase-IRIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
ColabNotebook = 'google.colab' in str(get_ipython())

if ColabNotebook:
    # monta G-drive en entorno COLAB
    from google.colab import drive
    drive.mount('/content/drive/')

    # carpeta donde se encuentran archivos .py auxiliares
    FUENTES_DIR = '/content/drive/MyDrive/Colab Notebooks/FUENTES/'
    DATOS_DIR = '/content/drive/MyDrive/Colab Notebooks/DATOS/'      # carpeta donde se encuentran los datasets
else:
    # configuración para notebook con instalación LOCAL
    FUENTES_DIR = '../Fuentes'         # carpeta donde se encuentran archivos .py auxiliares
    DATOS_DIR   = '../Datos/' # carpeta donde se encuentran los datasets

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

Mounted at /content/drive/


In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
from sklearn import preprocessing, metrics, model_selection

import time
#from matplotlib import pyplot as plt
from matplotlib import pylab as plt
from IPython import display

#from grafica import *
#from ClassRNMulticlase import RNMulticlase

In [3]:
datos = pd.read_csv(DATOS_DIR + 'iris.csv')
datos

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
X = np.array([[-1.73,-0.05,-1.38,-1.31],
              [-0.37,-1.62, 0.22, 0.18],
              [ 1.11,-0.05, 0.93, 1.54],
              [-0.99, 0.39,-1.44,-1.31],
              [ 1.73, 1.29, 1.46, 1.81]])
Y=np.array([[1,0,0],
            [0,1,0],
            [0,0,1],
            [1,0,0],
            [0,0,1]])

In [5]:
W = np.array([[-1.47, 1.93, 2.13,-2.49],
              [ 0.79,-1.38, 3.36,-3.57],
              [-1.57,-0.99, -6.17, 3.92]])

b = np.array([[-2.56],
              [-0.35],
              [-7.03]])

In [6]:
e = 0  # nro. de ejemplo a introducir a la red
xi = X[e:e+1, :]  #fila e de X
yi = Y[e:e+1, :]  # respuesta esperada para el ejemplo e
xi

array([[-1.73, -0.05, -1.38, -1.31]])

In [7]:
yi

array([[1, 0, 0]])

In [8]:
netas = W @ xi.T + b
print("neta \n", np.round(netas,2))
salidas = 1.0/(1+np.exp(-netas))
print("salidas = \n", np.round(salidas,4))

neta 
 [[ 0.21]
 [-1.61]
 [-0.89]]
salidas = 
 [[0.5521]
 [0.1669]
 [0.2921]]


In [9]:
ErrorSalida = yi.T-salidas
print("ErrorSalida = \n", np.round(ErrorSalida,4))

deriv_Fun = salidas * (1-salidas)
print("deriv_Fun = \n", np.round(deriv_Fun,4))
delta = ErrorSalida * deriv_Fun
print("delta = \n", np.round(delta,4))

#print("W2.T = \n", np.round(W2.T,2))

ErrorSalida = 
 [[ 0.4479]
 [-0.1669]
 [-0.2921]]
deriv_Fun = 
 [[0.2473]
 [0.139 ]
 [0.2068]]
delta = 
 [[ 0.1108]
 [-0.0232]
 [-0.0604]]


In [10]:
delta.shape

(3, 1)

In [11]:
# corregir los pesos
alfa=0.1

W = W + alfa * delta @ xi
b = b + alfa * delta

print("W = \n", np.round(W,2))
print("b = \n", np.round(b,2))


W = 
 [[-1.49  1.93  2.11 -2.5 ]
 [ 0.79 -1.38  3.36 -3.57]
 [-1.56 -0.99 -6.16  3.93]]
b = 
 [[-2.55]
 [-0.35]
 [-7.04]]


In [12]:
netas = W @ xi.T + b
salidas = 1.0/(1+np.exp(-netas))
print("salidas = \n", np.round(salidas,2))

ErrorSalidaNew = yi.T-salidas
print("ErrorSalida = \n", np.round(ErrorSalidaNew,4))

salidas = 
 [[0.57]
 [0.16]
 [0.28]]
ErrorSalida = 
 [[ 0.4272]
 [-0.1645]
 [-0.2827]]


In [13]:
print("Error inicial = ", np.sum(ErrorSalida**2))
print("Error luego de la correccion = ", np.round(np.sum(ErrorSalidaNew**2),4))

Error inicial =  0.31382859740694274
Error luego de la correccion =  0.2894
